SELECT * 
FROM 
    (
        SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
        FROM ONLINE_SALE

        UNION ALL

        SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
        FROM OFFLINE_SALE
    ) as ts
WHERE ts.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY 
    ts.SALES_DATE ASC,
    ts.PRODUCT_ID ASC,
    ts.USER_ID ASC;