SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO a
WHERE FAVORITES = (SELECT MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE HAVING a.FOOD_TYPE = FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;

# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO;
