SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o on p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE like '2022-05%'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC