SELECT b.USER_ID, b.NICKNAME, SUM(a.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_USER b ON a.WRITER_ID = b.USER_ID
WHERE STATUS = 'DONE' 
GROUP BY a.WRITER_ID
HAVING SUM(a.PRICE) >= 700000
ORDER BY TOTAL_SALES asc;
