SELECT a.ID as ID, a.GENOTYPE as GENOTYPE, b.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA a
JOIN ECOLI_DATA b ON a.PARENT_ID = b.ID
WHERE a.PARENT_ID IS NOT NULL
AND a.GENOTYPE & b.GENOTYPE >= b.GENOTYPE
ORDER BY id asc;