select YEAR(A.DIFFERENTIATION_DATE) as "YEAR", B.MAX_SIZE - SIZE_OF_COLONY as "YEAR_DEV", A.ID
from ECOLI_DATA A
join (
        select year(DIFFERENTIATION_DATE) as YEAR,
                max(SIZE_OF_COLONY) as MAX_SIZE
        from ECOLI_DATA
        GROUP By year(DIFFERENTIATION_DATE)
    ) B
    on YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR(DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC 
