SELECT a.ID, b.FISH_NAME, a.LENGTH
FROM FISH_INFO a
JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
WHERE a.LENGTH = (SELECT MAX(c.LENGTH) FROM FISH_INFO c WHERE a.FISH_TYPE = c.FISH_TYPE)
ORDER BY a.ID asc;