SELECT b.INGREDIENT_TYPE as INGREDIENT_TYPE, SUM(a.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF a
JOIN ICECREAM_INFO b ON b.FLAVOR = a.FLAVOR
GROUP BY b.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER asc;

# select * from FIRST_HALF;
# select * from ICECREAM_INFO;
