SELECT a.CATEGORY as CATEGORY, SUM(b.SALES) as TOTAL_SALES
FROM BOOK a
JOIN BOOK_SALES b ON a.BOOK_ID = b.BOOK_ID
WHERE b.SALES_DATE between DATE('2022-01-01') and DATE('2022-01-31')
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY;